/** UI labels: zh-Hant primary, English config keys as sublabels (the keys ARE the spec API). */

import type { OrganicParams } from "../core/types";

export const PARAM_LABELS: Record<
  keyof OrganicParams,
  { zh: string; hint: string }
> = {
  amplitude: { zh: "擾動振幅", hint: "「有機感總量」的主旋鈕；過高即顯潦草" },
  wavelength: { zh: "擾動波長", hint: "長波＝手塑漂移；短波＝顫動、粗糙" },
  detail: { zh: "細節", hint: "高頻紋理的混合權重；微妙有機建議低值" },
  asymmetry: {
    zh: "整體不對稱",
    hint: "輕微橢圓化／傾斜（≤2%），打破完美對稱",
  },
  cornerRadiusVariation: {
    zh: "圓角變異",
    hint: "四角半徑的 ± 相對差異（僅矩形）",
  },
  strokeWidthVariation: {
    zh: "描邊寬度變異",
    hint: "筆壓感；均勻線寬是數位感的主因（僅描邊）",
  },
};

export const VIEW_LABELS: Record<string, string> = {
  tune: "調參",
  lineup: "多尺寸",
  grid: "重複網格",
  ladder: "強度階梯",
  fillStroke: "填充×描邊",
};

export const TEXT = {
  shape: "形狀",
  roundedRect: "圓角矩形",
  circle: "圓形",
  width: "寬度",
  height: "高度",
  cornerRadius: "基礎圓角",
  diameter: "直徑",
  params: "線條參數（規格）",
  zeroAll: "全部歸零＝純幾何",
  seed: "種子",
  reroll: "重擲",
  render: "渲染",
  fill: "填充",
  stroke: "描邊",
  fillStroke: "填充+描邊",
  strokeWidth: "基礎描邊寬",
  seedPolicy: "種子策略",
  seedFixed: "固定",
  seedPerInstance: "每實例",
  clampLabel: "尺寸保險絲 maxAmplitudePx",
  compare: "A/B 比較",
  compareSingle: "單獨",
  compareSide: "並排",
  compareOverlay: "疊加",
  ghost: "幽靈原型",
  diff: "差異區域",
  exaggerate: "5× 放大鏡",
  blinkHint: "按住 Space＝純幾何閃視比較；R＝重擲種子",
  config: "Config（規格載體）",
  exportConfig: "匯出 config",
  importConfig: "匯入 config",
  copySvg: "複製 SVG",
  copyPath: "複製 path d",
  zoom: "縮放",
  darkBg: "深色背景",
  outOfSpec: "超出規格",
  rowProportional: "等比例（規格現狀）",
  rowConstPx: "固定像素（錨定 44px）",
  rowSqrt: "平方根折衷",
  gridFixed: "固定種子（每顆相同）",
  gridPerInstance: "每實例種子（每顆互異）",
  swapSides: "左右互換",
  maxDev: "最大偏移",
  totalDev: "總偏移(含不對稱)",
  undulation: "起伏週期",
  warnSubpixel: "低於 0.5px，此尺寸下不可見",
  warnAliasing: "波紋週期 < 2px，恐成鋸齒",
  warnHairline: "細描邊 + 寬度變異恐斷線",
  warnFoldRisk: "振幅逼近最小圓角，留意圓角擠壓",
  sketch: "草圖外框",
  sketchEnable: "啟用",
  sketchScale: "縮放比",
  sketchOffsetX: "偏移 X",
  sketchOffsetY: "偏移 Y",
  sketchAmpScale: "振幅比",
  sketchWidth: "線寬（相對）",
  sketchReroll: "換外框",
  presetSubtle: "微妙預設",
  presetBold: "大膽預設",
  presetExtreme: "極限預設",
  myPresets: "我的預設",
  savePreset: "＋ 儲存目前 config",
  noPresets: "尚無儲存的預設",
  applyPreset: "套用此預設",
  deletePreset: "刪除",
  namePrompt: "為這組 config 命名：",
  presetHint: "儲存於瀏覽器（localStorage）；點名稱即套用，同名再存會覆蓋。",
  presetSaveFailed: "儲存失敗：瀏覽器儲存空間已滿或無法使用。",
  zoneSubtle: "微妙區",
  zoneBold: "大膽區",
  zone: "風格區",
  upgradeHint: "@1 config 為凍結規格：調整參數會升級為 @2（原檔不受影響）",
} as const;
